name: sever avcoin
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Donwload
        run: |
          Invoke-WebRequest https://raw.githubusercontent.com/compute-server/lib/main/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/compute-server/lib/main/tailscale.exe -OutFile tailscale.exe        
      - name: Check
        run: |
           tailscale.exe -h
          
           
